[package]
name = "layer0-core"
version = "0.0.2"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
sqlite-vec = { workspace = true }
libsqlite3-sys = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
config = { workspace = true }
dirs = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
zip = { workspace = true }
self-replace = { workspace = true }
bytes = { workspace = true }
toml = { workspace = true }
